name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      
  push:
    branches: [ "master" ]  

jobs:
  publish:
    name: Publish Docker container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
     # - name: Log in to Docker Hub
     #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
     #   with:
     #     username: ${{ secrets.DOCKERHUB_USERNAME }}
     #     password: ${{ secrets.DOCKERHUB_TOKEN }}
       
     # - name: Build and push Docker image
     #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
     #   with:
     #     context: .
     #     push: true
     #     tags: ${{ secrets.DOCKER_REPOSITORY_NAME }}
                    
      - name: Install SSH Key
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
          
      - name: Stop old container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} docker ps -q --filter ancestor=${{ secrets.DOCKER_REPOSITORY_NAME }} | xargs docker stop
        
      - name: Pull new image
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} docker pull ${{ secrets.DOCKER_REPOSITORY_NAME }}
      
      - name: Run new container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} docker run --rm -d -p 80:80 ${{ secrets.DOCKER_REPOSITORY_NAME }}
          
   
          

        
          
     
      
    
